### ISSUE TITLE
Filtered item still visible

### ISSUE THREAD

**Issue by mortensassi** [metafizzy/isotope#1486]
My filter seems to work just fine. In the browsers' inspector i can see that the affected elements inline-style get changed but after that nothing happens.

**Test case:** https://codepen.io/moesphemie/pen/zXewPY

**Comment by mortensassi** [comment]
Okay i got it – Two problems:

* `<option value="">All</option>`'s value should be empty
* Filtering by a year as a class,  such as `.2019` results in an error:

```error
matches-selector.js:50 Uncaught DOMException: Failed to execute 'matches' on 'Element': '.2019' is not a valid selector.
    at matchesSelector (http://localhost:3000/wp-content/themes/myTHEME/dist/scripts/app.bundle.js:4064:33)
    at http://localhost:3000/wp-content/themes/myTHEME/dist/scripts/app.bundle.js:482:14
    at SubClass.proto._filter (http://localhost:3000/wp-content/themes/myTHEME/dist/scripts/app.bundle.js:444:23)
    at SubClass.proto.arrange (http://localhost:3000/wp-content/themes/myTHEME/dist/scripts/app.bundle.js:368:25)
    at HTMLDivElement.<anonymous> (http://localhost:3000/wp-content/themes/myTHEME/dist/scripts/app.bundle.js:3883:11)
matchesSelector @ matches-selector.js:50
(anonymous) @ isotope.js:289
proto._filter @ isotope.js:251
proto.arrange @ isotope.js:175
(anonymous) @ filter.js:41
```

So adding a `.year-` fixed it!

**Comment by desandro** [comment]
Thanks for following up.
